### ISSUE TITLE
[BUG] - enhanced Plex not working

### ISSUE THREAD

**Issue by listiges-kaenguru** [linuxserver/Heimdall-Apps#697] opened 2024-02-26 08:07 UTC
**Describe the bug**
Origin: https://github.com/linuxserver/Heimdall/issues/1301

Enhanced Config not showing on creation of ne Plex App.

**To Reproduce**
1. Go to 'create Item'
2. Click on 'Application Type'
3. Scroll down to 'Plex'

**Expected behavior**
Enhanced Config on bottom of Page

**Screenshots**
see linked Issue in Heimdall-Rep

**Version info (please complete the following information):**
 - Heimdall: 2.6.1

**Additional context**
see linked Issue in Heimdall-Rep

**Comment by mvdkleijn** [comment] 2024-02-27 10:02
I don't see an immediate reason why it would not work. Last changes were whitespace related so don't think that would be a problem.

Based on the description, I'd almost say the main index json is messed up but I'd have to look at that a little later.

**Comment by mvdkleijn** [comment] 2024-02-27 16:11
Closing because I cannot reproduce. It works fine for me using latest Heimdall & up-to-date app list.

![heimdall-Screenshot from 2024-02-27 17-09-25](https://github.com/linuxserver/Heimdall-Apps/assets/431452/ea422dce-a7fc-46aa-8f02-ad4a452857b0)

**Closed by mvdkleijn** 2024-02-27 16:11 UTC
Labels: bug
